import numpy as np
import ROOT as rt

sample_configurables = {
'SMST2bW' : {
  #'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
  'legend' : 'SMS-T2bW',
  'color'  : rt.kMagenta,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMST2bW_isB' : {
  #'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
  'legend' : 'B SMS-T2bW',
  'color'  : rt.kRed,
  'style'  : 1,
  'width'  : 3,
  'fill'  : rt.kRed,
  'fill_style'  : 1001,
             },
'SMST2bW_isC' : {
  #'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
  'legend' : 'C SMS-T2bW',
  'color'  : rt.kCyan,
  'style'  : 1,
  'width'  : 3,
  'fill'  : rt.kCyan,
  'fill_style'  : 3005,
             },
'SMST2bW_isLight' : {
  #'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
  'legend' : 'Light SMS-T2bW',
  'color'  : rt.kBlue,
  'style'  : 1,
  'width'  : 3,
  'fill'  : rt.kBlue,
  'fill_style'  : 3004,
             },
#'SMS_TChiWZ_mZMin' : {
##  'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
#  'legend' : 'SMS-TChiWZ mZMin',
#  'color'  : rt.kAzure,
#  'style'  : 1,
#  'width'  : 3,
#  'fill'  : None,
#  'fill_style'  : None,
#             },
##'SMS_TChiWZ' : {
###  'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
##  'legend' : 'SMS-TChiWZ',
##  'color'  : rt.kAzure,
##  'style'  : 1,
##  'width'  : 3,
##  'fill'  : None,
##  'fill_style'  : None,
##             },
#'SMS_TSlepSlep' : {
##  'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow b #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{+}}}} (W^{+} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}})',
#  'legend' : 'SMS-TSlepSlep',
#  'color'  : rt.kAzure,
#  'style'  : 1,
#  'width'  : 3,
#  'fill'  : None,
#  'fill_style'  : None,
#             },
'SMS_T2bW_420' : {
  'legend' : 'SMS-T2bW',
  'color'  : rt.kMagenta+4,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS_T2bW_490' : {
  'legend' : 'SMS-T2bW',
  'color'  : rt.kViolet-5,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMST2tt' : {
  'legend' : 'SMS-T2tt',
  'color'  : rt.kMagenta+4,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS_T2_4bd_490' : {
  'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow bf#bar{f} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}}',
  #'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet-5,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS_T2_4bd_420' : {
  'legend' : 'pp #rightarrow #lower[0.1]{#tilde{#lower[-0.1]{t}}} #lower[0.05]{#bar{#tilde{#lower[-0.05]{t}}}} ; #lower[0.1]{#tilde{#lower[-0.1]{t}}} #rightarrow bf#bar{f} #lower[-0.15]{#tilde{#chi}#lower[-0.1]{_{1}}#kern[-0.7]{#lower[0.3]{^{0}}}}',
  #'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet+5,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'data'   : {
  'legend' : 'MuonEG Data',
  'color'  : rt.kBlack,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlack,
  'fill_style'   : 1001,
             },
'data_muoneg'   : {
  'legend' : 'MuonEG Data',
  'color'  : rt.kBlack,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlack,
  'fill_style'   : 1001,
             },
'data_met'   : {
  'legend' : 'MuonEG Data',
  'color'  : rt.kBlack,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlack,
  'fill_style'   : 1001,
             },
#'Tot2017'   : {
#  'legend' : 'Total',
#  'color'  : rt.kGreen+3,
#  'style'  : 1,
#  'width'  : 3,
#  'fill'   : rt.kGreen+3,
#  'fill_style'   : 1001,
#             },
'TTJets2017'   : {
  'legend' : 't#bar{t}+jets',
  'color'  : rt.kGreen+3,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kGreen+3,
  'fill_style'   : 1001,
             },
'WJets2017'   : {
  'legend' : 'W+jets',
  'color'  : rt.kOrange+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kOrange+1,
  'fill_style'   : 1001,
             },
'TTV2017'   : {
  'legend' : 't#bar{t}+V',
  'color'  : rt.kYellow+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kYellow+1,
  'fill_style'   : 1001,
             },
'ST2017'   : {
  'legend' : 'ST',
  'color'  : rt.kCyan-9,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan-9,
  'fill_style'   : 1001,
             },
'ZDY2017'   : {
  'legend' : 'Z/DY+jets',
  'color'  : rt.kBlue+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlue+1,
  'fill_style'   : 1001,
             },
'VV2017'   : {
  'legend' : 'WW',
  'color'  : rt.kCyan+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan+1,
  'fill_style'   : 1001,
             },

#Flavors
'Tot2017_isB'   : {
  'legend' : 'B Flavor SVs',
  'color'  : rt.kRed,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kRed,
  'fill_style'   : 1001,
             },
'Tot2017_isC'   : {
  'legend' : 'C Flavor SVs',
  'color'  : rt.kCyan,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan,
  'fill_style'   : 3005,
             },
'Tot2017_isLight'   : {
  'legend' : 'Light Flavor SVs',
  'color'  : rt.kBlue,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlue,
  'fill_style'   : 3004,
             },
#'TTJets2017_isB'   : {
#  'legend' : 't#bar{t}+jets b',
#  'color'  : rt.kGreen+3,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kGreen+3,
#  'fill_style'   : 1001,
#             },
#'TTJets2017_isC'   : {
#  'legend' : 't#bar{t}+jets c',
#  'color'  : rt.kGreen+6,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kGreen+6,
#  'fill_style'   : 3005,
#             },
#'TTJets2017_isLight'   : {
#  'legend' : 't#bar{t}+jets light',
#  'color'  : rt.kGreen-3,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kGreen-3,
#  'fill_style'   : 3004,
#             },
#'ST2017_isB'   : {
#  'legend' : 'ST b',
#  'color'  : rt.kCyan-9,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kCyan-9,
#  'fill_style'   : 1001,
#             },
#'ST2017_isC'   : {
#  'legend' : 'ST c',
#  'color'  : rt.kCyan-6,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kCyan-6,
#  'fill_style'   : 3005,
#             },
#'ST2017_isLight'   : {
#  'legend' : 'ST light',
#  'color'  : rt.kCyan-3,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kCyan-3,
#  'fill_style'   : 3004,
#             },
#'TTV2017_isB'   : {
#  'legend' : 't#bar{t}+V b',
#  'color'  : rt.kYellow+1,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kYellow+1,
#  'fill_style'   : 1001,
#             },
#'TTV2017_isC'   : {
#  'legend' : 't#bar{t}+V c',
#  'color'  : rt.kYellow-2,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kYellow-2,
#  'fill_style'   : 3005,
#             },
#'TTV2017_isLight'   : {
#  'legend' : 't#bar{t}+V b',
#  'color'  : rt.kYellow+4,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kYellow+4,
#  'fill_style'   : 3004,
#             },
#'WJets2017_isB'   : {
#  'legend' : 'W+jets b',
#  'color'  : rt.kOrange+1,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kOrange+1,
#  'fill_style'   : 1001,
#             },
#'WJets2017_isC'   : {
#  'legend' : 'W+jets c',
#  'color'  : rt.kOrange-2,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kOrange-2,
#  'fill_style'   : 3005,
#             },
#'WJets2017_isLight'   : {
#  'legend' : 'W+jets light',
#  'color'  : rt.kOrange+4,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kOrange+4,
#  'fill_style'   : 3004,
#             },
#'DY2017_isB'   : {
#  'legend' : 'DY+jets b',
#  'color'  : rt.kBlue+1,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kBlue+1,
#  'fill_style'   : 1001,
#             },
#'DY2017_isC'   : {
#  'legend' : 'DY+jets c',
#  'color'  : rt.kBlue-2,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kBlue-2,
#  'fill_style'   : 3005,
#             },
#'DY2017_isLight'   : {
#  'legend' : 'DY+jets light',
#  'color'  : rt.kBlue+4,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kBlue+4,
#  'fill_style'   : 3004,
#             },
#'VV2017_isB'   : {
#  'legend' : 'VV b',
#  'color'  : rt.kRed+1,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kRed+1,
#  'fill_style'   : 1001,
#             },
#'VV2017_isC'   : {
#  'legend' : 'VV c',
#  'color'  : rt.kRed-2,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kRed-2,
#  'fill_style'   : 3005,
#             },
#'VV2017_isLight'   : {
#  'legend' : 'VV light',
#  'color'  : rt.kRed+4,
#  'style'  : 1,
#  'width'  : 1,
#  'fill'   : rt.kRed+4,
#  'fill_style'   : 3004,
#             },

}

######   configuration template   ######
"""
'Null'    : {
  'xlabel'  : None,
  'ylabel'  : None,
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
"""
######  end template  ######
plot_configurables = {
'NS_objects'    : {
  'xlabel'  : None,
  'ylabel'  : 'a.u.',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NISR_objects'    : {
  'xlabel'  : None,
  'ylabel'  : 'a.u.',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
#'MET'    : {
#  'xlabel'  : 'MET',
#  'ylabel'  : 'Events',
#  'nbins_x' : None,
#  'xmin'    : None,
#  'xmax'    : None,
#  'nbinsy'  : None,
#  'ymin'    : None,
#  'ymax'    : None,
#  'log'     : True,
#              },
#'MET_1bin'    : {
#  'xlabel'  : 'MET',
#  'ylabel'  : 'Events',
#  'nbins_x' : None,
#  'xmin'    : None,
#  'xmax'    : None,
#  'nbinsy'  : None,
#  'ymin'    : None,
#  'ymax'    : None,
#  'log'     : True,
#              },
'PT_Eta'    : {
  'xlabel'  : 'SV p_{T} [GeV]',
  'ylabel'  : 'SV #eta',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'ProbB_SV'    : {
  'xlabel'  : 'Prob isB',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT'    : {
  'xlabel'  : 'SV p_{T} [GeV]',
  'ylabel'  : 'SV eff',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_SV'    : {
  'xlabel'  : 'SV p_{T} [GeV]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_SV_1GeV'    : {
  'xlabel'  : 'SV p_{T} [GeV]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_SV_1bin'    : {
  'xlabel'  : 'SV p_{T} [GeV]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Eta'    : {
  'xlabel'  : 'SV #eta',
  'ylabel'  : 'SV eff',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Eta_SV'    : {
  'xlabel'  : 'SV #eta',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Eta_SV_1bin'    : {
  'xlabel'  : 'SV #eta',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Eta_SV_2bin'    : {
  'xlabel'  : 'SV #eta',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Eta_SV_2binV2'    : {
  'xlabel'  : 'SV #eta',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'M_SV'    : {
  'xlabel'  : 'SV M [GeV]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 5,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Ndof_SV'    : {
  'xlabel'  : 'SV N_{dof}',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Dxy_SV'    : {
  'xlabel'  : 'SV d_{xy} [cm]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 2.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'DxySig_SV'    : {
  'xlabel'  : 'SV SIP_{xy}',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3d_SV'    : {
  'xlabel'  : 'SV d_{3D} [cm]',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3dSig_SV'    : {
  'xlabel'  : 'SV SIP_{3D}',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'CosTheta_SV'    : {
  'xlabel'  : 'Cos(#theta)',
  'ylabel'  : 'SVs',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR'    : {
  'xlabel'  : 'RISR',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MPE'    : {
  'xlabel'  : 'MPE',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'dphiMETV_RISR'    : {
  'xlabel'  : 'dphiMETV',
  'ylabel'  : 'RISR',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PTCM_RISR'    : {
  'xlabel'  : 'PTCM',
  'ylabel'  : 'RISR',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'dphiCMI_PTCM'    : {
  'xlabel'  : 'dphiCMI',
  'ylabel'  : 'PTCM',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'gammaT_RISR'    : {
  'xlabel'  : '#gamma_{T}',
  'ylabel'  : 'R_{ISR}',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 1.5,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PTISR_RISR'    : {
  'xlabel'  : 'PTISR',
  'ylabel'  : 'RISR',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_MPE'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'M_{#perp}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_MPE_v2'    : {
  'xlabel'  : 'R_{ISR}',
  'ylabel'  : 'M_{#perp}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : 0.,
  'ymax'    : 120.,
  'log'     : True,
              },
'RISR_ProbB'    : {
  'xlabel'  : 'RISR',
  'ylabel'  : 'Max ProbB',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Ndof_Eta'    : {
  'xlabel'  : 'N_{dof} SV',
  'ylabel'  : '#eta SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Ndof_PT'    : {
  'xlabel'  : 'N_{dof} SV',
  'ylabel'  : 'p_{T}',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Dxy_Eta'    : {
  'xlabel'  : 'd_{xy} SV',
  'ylabel'  : '#eta SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'Dxy_PT'    : {
  'xlabel'  : 'd_{xy} SV',
  'ylabel'  : 'p_{T} SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3d_Eta'    : {
  'xlabel'  : 'd_{3D} SV',
  'ylabel'  : '#eta SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3d_PT'    : {
  'xlabel'  : 'd_{3D} SV',
  'ylabel'  : 'p_{T} SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3dSig_Eta'    : {
  'xlabel'  : 'SIP_{3D}',
  'ylabel'  : '#eta',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'D3dSig_PT'    : {
  'xlabel'  : 'SIP_{3D} SV',
  'ylabel'  : 'p_{T} SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'CosTheta_Eta'    : {
  'xlabel'  : 'Cos(#theta) SV',
  'ylabel'  : '#eta SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'CosTheta_PT'    : {
  'xlabel'  : 'CosTheta SV',
  'ylabel'  : 'p_{T} SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'M_Eta'    : {
  'xlabel'  : 'SV M [GeV]',
  'ylabel'  : '#eta SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'M_PT'    : {
  'xlabel'  : 'SV M [GeV]',
  'ylabel'  : 'p_{T} SV',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
}

selections = [
                                 'ntrk',
                                 'nojets',
                                 'all',
                                 'discr',
                                 'discr_ntrk',
                                 'discr_div_nojets',
                                 'discr_ntrk_div_nojets',
                                 'discr_ntrk_div_ntrk',
                                 'all_div_nojets',
                                 'all_div_ntrk',
#        '1l_ge1ssv',
#               'base',
#        'emu_sv',
#        'emu_lowmet',
#        'emu_lowmet_sv',
#        'emu_highmet',
#        'emu_highmet_sv',
#        'base_2lep',
#        'base_2lep_ge2jet',
#        '2lep_sv',
#        'base_1lep',
#        'base_1lep_2jet',
        '1lep_sv',
#        '1lep_l0p8',
#        '1lep_l0p8_sv',
#        '0lep',
#        '0lep_sv',
#               'gold_nos_noisrb',
#               'gold_nos_isrb',
#               'gold_ge1ssv_noisrb',
#               'gold_ge1ssv_isrb',
#               'gold_ge1ssv_central_noisrb',
#               'gold_ge1ssv_central_isrb',
#               'gold_ge1ssv_forward_noisrb',
#               'gold_ge1ssv_forward_isrb',
#               'gold_1sj_noisrb',
#               'gold_1sj_isrb',
#               'gold_1sj_1sb_noisrb',
#               'gold_1sj_1sb_isrb',
#               'gold_1sj_ge1ssv_noisrb',
#               'gold_1sj_ge1ssv_isrb',
#               'gold_1sj_ge1ssv_central_noisrb',
#               'gold_1sj_ge1ssv_central_isrb',
#               'gold_1sj_ge1ssv_forward_noisrb',
#               'gold_1sj_ge1ssv_forward_isrb',
#               'gold_1sj_1sb_ge1ssv_noisrb',
#               'gold_1sj_1sb_ge1ssv_isrb',
#               'gold_1sj_1sb_ge1ssv_central_noisrb',
#               'gold_1sj_1sb_ge1ssv_central_isrb',
#               'gold_1sj_1sb_ge1ssv_forward_noisrb',
#               'gold_1sj_1sb_ge1ssv_forward_isrb',
#               'gold_2sj_noisrb',
#               'gold_2sj_isrb',
#               'gold_2sj_1sb_noisrb',
#               'gold_2sj_1sb_isrb',
#               'gold_2sj_2sb_noisrb',
#               'gold_2sj_2sb_isrb',
#               'gold_3sj_noisrb',
#               'gold_3sj_isrb',
#               'gold_3sj_ge1sb_noisrb',
#               'gold_3sj_ge1sb_isrb',
#               'gold_ge4sj_noisrb',
#               'gold_ge4sj_isrb',
#               'posmu_gold_nos_noisrb',
#               'posmu_gold_nos_isrb',
#               'posmu_gold_ge1ssv_noisrb',
#               'posmu_gold_ge1ssv_isrb',
#               'posmu_gold_ge1ssv_central_noisrb',
#               'posmu_gold_ge1ssv_central_isrb',
#               'posmu_gold_ge1ssv_forward_noisrb',
#               'posmu_gold_ge1ssv_forward_isrb',
#               'posmu_gold_1sj_noisrb',
#               'posmu_gold_1sj_isrb',
#               'posmu_gold_1sj_1sb_noisrb',
#               'posmu_gold_1sj_1sb_isrb',
#               'posmu_gold_1sj_ge1ssv_noisrb',
#               'posmu_gold_1sj_ge1ssv_isrb',
#               'posmu_gold_1sj_ge1ssv_central_noisrb',
#               'posmu_gold_1sj_ge1ssv_central_isrb',
#               'posmu_gold_1sj_ge1ssv_forward_noisrb',
#               'posmu_gold_1sj_ge1ssv_forward_isrb',
#               'posmu_gold_1sj_1sb_ge1ssv_noisrb',
#               'posmu_gold_1sj_1sb_ge1ssv_isrb',
#               'posmu_gold_1sj_1sb_ge1ssv_central_noisrb',
#               'posmu_gold_1sj_1sb_ge1ssv_central_isrb',
#               'posmu_gold_1sj_1sb_ge1ssv_forward_noisrb',
#               'posmu_gold_1sj_1sb_ge1ssv_forward_isrb',
#               'posmu_gold_2sj_noisrb',
#               'posmu_gold_2sj_isrb',
#               'posmu_gold_2sj_1sb_noisrb',
#               'posmu_gold_2sj_1sb_isrb',
#               'posmu_gold_2sj_2sb_noisrb',
#               'posmu_gold_2sj_2sb_isrb',
#               'posmu_gold_3sj_noisrb',
#               'posmu_gold_3sj_isrb',
#               'posmu_gold_3sj_ge1sb_noisrb',
#               'posmu_gold_3sj_ge1sb_isrb',
#               'posmu_gold_ge4sj_noisrb',
#               'posmu_gold_ge4sj_isrb',
#               'negmu_gold_nos_noisrb',
#               'negmu_gold_nos_isrb',
#               'negmu_gold_ge1ssv_noisrb',
#               'negmu_gold_ge1ssv_isrb',
#               'negmu_gold_ge1ssv_central_noisrb',
#               'negmu_gold_ge1ssv_central_isrb',
#               'negmu_gold_ge1ssv_forward_noisrb',
#               'negmu_gold_ge1ssv_forward_isrb',
#               'negmu_gold_1sj_noisrb',
#               'negmu_gold_1sj_isrb',
#               'negmu_gold_1sj_1sb_noisrb',
#               'negmu_gold_1sj_1sb_isrb',
#               'negmu_gold_1sj_ge1ssv_noisrb',
#               'negmu_gold_1sj_ge1ssv_isrb',
#               'negmu_gold_1sj_ge1ssv_central_noisrb',
#               'negmu_gold_1sj_ge1ssv_central_isrb',
#               'negmu_gold_1sj_ge1ssv_forward_noisrb',
#               'negmu_gold_1sj_ge1ssv_forward_isrb',
#               'negmu_gold_1sj_1sb_ge1ssv_noisrb',
#               'negmu_gold_1sj_1sb_ge1ssv_isrb',
#               'negmu_gold_1sj_1sb_ge1ssv_central_noisrb',
#               'negmu_gold_1sj_1sb_ge1ssv_central_isrb',
#               'negmu_gold_1sj_1sb_ge1ssv_forward_noisrb',
#               'negmu_gold_1sj_1sb_ge1ssv_forward_isrb',
#               'negmu_gold_2sj_noisrb',
#               'negmu_gold_2sj_isrb',
#               'negmu_gold_2sj_1sb_noisrb',
#               'negmu_gold_2sj_1sb_isrb',
#               'negmu_gold_2sj_2sb_noisrb',
#               'negmu_gold_2sj_2sb_isrb',
#               'negmu_gold_3sj_noisrb',
#               'negmu_gold_3sj_isrb',
#               'negmu_gold_3sj_ge1sb_noisrb',
#               'negmu_gold_3sj_ge1sb_isrb',
#               'negmu_gold_ge4sj_noisrb',
#               'negmu_gold_ge4sj_isrb',
#               'posel_gold_nos_noisrb',
#               'posel_gold_nos_isrb',
#               'posel_gold_ge1ssv_noisrb',
#               'posel_gold_ge1ssv_isrb',
#               'posel_gold_ge1ssv_central_noisrb',
#               'posel_gold_ge1ssv_central_isrb',
#               'posel_gold_ge1ssv_forward_noisrb',
#               'posel_gold_ge1ssv_forward_isrb',
#               'posel_gold_1sj_noisrb',
#               'posel_gold_1sj_isrb',
#               'posel_gold_1sj_1sb_noisrb',
#               'posel_gold_1sj_1sb_isrb',
#               'posel_gold_1sj_ge1ssv_noisrb',
#               'posel_gold_1sj_ge1ssv_isrb',
#               'posel_gold_1sj_ge1ssv_central_noisrb',
#               'posel_gold_1sj_ge1ssv_central_isrb',
#               'posel_gold_1sj_ge1ssv_forward_noisrb',
#               'posel_gold_1sj_ge1ssv_forward_isrb',
#               'posel_gold_1sj_1sb_ge1ssv_noisrb',
#               'posel_gold_1sj_1sb_ge1ssv_isrb',
#               'posel_gold_1sj_1sb_ge1ssv_central_noisrb',
#               'posel_gold_1sj_1sb_ge1ssv_central_isrb',
#               'posel_gold_1sj_1sb_ge1ssv_forward_noisrb',
#               'posel_gold_1sj_1sb_ge1ssv_forward_isrb',
#               'posel_gold_2sj_noisrb',
#               'posel_gold_2sj_isrb',
#               'posel_gold_2sj_1sb_noisrb',
#               'posel_gold_2sj_1sb_isrb',
#               'posel_gold_2sj_2sb_noisrb',
#               'posel_gold_2sj_2sb_isrb',
#               'posel_gold_3sj_noisrb',
#               'posel_gold_3sj_isrb',
#               'posel_gold_3sj_ge1sb_noisrb',
#               'posel_gold_3sj_ge1sb_isrb',
#               'posel_gold_ge4sj_noisrb',
#               'posel_gold_ge4sj_isrb',
#               'negel_gold_nos_noisrb',
#               'negel_gold_nos_isrb',
#               'negel_gold_ge1ssv_noisrb',
#               'negel_gold_ge1ssv_isrb',
#               'negel_gold_ge1ssv_central_noisrb',
#               'negel_gold_ge1ssv_central_isrb',
#               'negel_gold_ge1ssv_forward_noisrb',
#               'negel_gold_ge1ssv_forward_isrb',
#               'negel_gold_1sj_noisrb',
#               'negel_gold_1sj_isrb',
#               'negel_gold_1sj_1sb_noisrb',
#               'negel_gold_1sj_1sb_isrb',
#               'negel_gold_1sj_ge1ssv_noisrb',
#               'negel_gold_1sj_ge1ssv_isrb',
#               'negel_gold_1sj_ge1ssv_central_noisrb',
#               'negel_gold_1sj_ge1ssv_central_isrb',
#               'negel_gold_1sj_ge1ssv_forward_noisrb',
#               'negel_gold_1sj_ge1ssv_forward_isrb',
#               'negel_gold_1sj_1sb_ge1ssv_noisrb',
#               'negel_gold_1sj_1sb_ge1ssv_isrb',
#               'negel_gold_1sj_1sb_ge1ssv_central_noisrb',
#               'negel_gold_1sj_1sb_ge1ssv_central_isrb',
#               'negel_gold_1sj_1sb_ge1ssv_forward_noisrb',
#               'negel_gold_1sj_1sb_ge1ssv_forward_isrb',
#               'negel_gold_2sj_noisrb',
#               'negel_gold_2sj_isrb',
#               'negel_gold_2sj_1sb_noisrb',
#               'negel_gold_2sj_1sb_isrb',
#               'negel_gold_2sj_2sb_noisrb',
#               'negel_gold_2sj_2sb_isrb',
#               'negel_gold_3sj_noisrb',
#               'negel_gold_3sj_isrb',
#               'negel_gold_3sj_ge1sb_noisrb',
#               'negel_gold_3sj_ge1sb_isrb',
#               'negel_gold_ge4sj_noisrb',
#               'negel_gold_ge4sj_isrb',
#               'silver_nos_noisrb',
#               'silver_nos_isrb',
#               'silver_ge1ssv_noisrb',
#               'silver_ge1ssv_isrb',
#               'silver_ge1ssv_central_noisrb',
#               'silver_ge1ssv_central_isrb',
#               'silver_ge1ssv_forward_noisrb',
#               'silver_ge1ssv_forward_isrb',
#               'silver_1sj_noisrb',
#               'silver_1sj_isrb',
#               'silver_1sj_1sb_noisrb',
#               'silver_1sj_1sb_isrb',
#               'silver_1sj_ge1ssv_noisrb',
#               'silver_1sj_ge1ssv_isrb',
#               'silver_1sj_ge1ssv_central_noisrb',
#               'silver_1sj_ge1ssv_central_isrb',
#               'silver_1sj_ge1ssv_forward_noisrb',
#               'silver_1sj_ge1ssv_forward_isrb',
#               'silver_1sj_1sb_ge1ssv_noisrb',
#               'silver_1sj_1sb_ge1ssv_isrb',
#               'silver_1sj_1sb_ge1ssv_central_noisrb',
#               'silver_1sj_1sb_ge1ssv_central_isrb',
#               'silver_1sj_1sb_ge1ssv_forward_noisrb',
#               'silver_1sj_1sb_ge1ssv_forward_isrb',
#               'silver_2sj_noisrb',
#               'silver_2sj_isrb',
#               'silver_2sj_1sb_noisrb',
#               'silver_2sj_1sb_isrb',
#               'silver_2sj_2sb_noisrb',
#               'silver_2sj_2sb_isrb',
#               'silver_3sj_noisrb',
#               'silver_3sj_isrb',
#               'silver_3sj_ge1sb_noisrb',
#               'silver_3sj_ge1sb_isrb',
#               'silver_ge4sj_noisrb',
#               'silver_ge4sj_isrb',
#               'posmu_silver_nos_noisrb',
#               'posmu_silver_nos_isrb',
#               'posmu_silver_ge1ssv_noisrb',
#               'posmu_silver_ge1ssv_isrb',
#               'posmu_silver_ge1ssv_central_noisrb',
#               'posmu_silver_ge1ssv_central_isrb',
#               'posmu_silver_ge1ssv_forward_noisrb',
#               'posmu_silver_ge1ssv_forward_isrb',
#               'posmu_silver_1sj_noisrb',
#               'posmu_silver_1sj_isrb',
#               'posmu_silver_1sj_1sb_noisrb',
#               'posmu_silver_1sj_1sb_isrb',
#               'posmu_silver_1sj_ge1ssv_noisrb',
#               'posmu_silver_1sj_ge1ssv_isrb',
#               'posmu_silver_1sj_ge1ssv_central_noisrb',
#               'posmu_silver_1sj_ge1ssv_central_isrb',
#               'posmu_silver_1sj_ge1ssv_forward_noisrb',
#               'posmu_silver_1sj_ge1ssv_forward_isrb',
#               'posmu_silver_1sj_1sb_ge1ssv_noisrb',
#               'posmu_silver_1sj_1sb_ge1ssv_isrb',
#               'posmu_silver_1sj_1sb_ge1ssv_central_noisrb',
#               'posmu_silver_1sj_1sb_ge1ssv_central_isrb',
#               'posmu_silver_1sj_1sb_ge1ssv_forward_noisrb',
#               'posmu_silver_1sj_1sb_ge1ssv_forward_isrb',
#               'posmu_silver_2sj_noisrb',
#               'posmu_silver_2sj_isrb',
#               'posmu_silver_2sj_1sb_noisrb',
#               'posmu_silver_2sj_1sb_isrb',
#               'posmu_silver_2sj_2sb_noisrb',
#               'posmu_silver_2sj_2sb_isrb',
#               'posmu_silver_3sj_noisrb',
#               'posmu_silver_3sj_isrb',
#               'posmu_silver_3sj_ge1sb_noisrb',
#               'posmu_silver_3sj_ge1sb_isrb',
#               'posmu_silver_ge4sj_noisrb',
#               'posmu_silver_ge4sj_isrb',
#               'negmu_silver_nos_noisrb',
#               'negmu_silver_nos_isrb',
#               'negmu_silver_ge1ssv_noisrb',
#               'negmu_silver_ge1ssv_isrb',
#               'negmu_silver_ge1ssv_central_noisrb',
#               'negmu_silver_ge1ssv_central_isrb',
#               'negmu_silver_ge1ssv_forward_noisrb',
#               'negmu_silver_ge1ssv_forward_isrb',
#               'negmu_silver_1sj_noisrb',
#               'negmu_silver_1sj_isrb',
#               'negmu_silver_1sj_1sb_noisrb',
#               'negmu_silver_1sj_1sb_isrb',
#               'negmu_silver_1sj_ge1ssv_noisrb',
#               'negmu_silver_1sj_ge1ssv_isrb',
#               'negmu_silver_1sj_ge1ssv_central_noisrb',
#               'negmu_silver_1sj_ge1ssv_central_isrb',
#               'negmu_silver_1sj_ge1ssv_forward_noisrb',
#               'negmu_silver_1sj_ge1ssv_forward_isrb',
#               'negmu_silver_1sj_1sb_ge1ssv_noisrb',
#               'negmu_silver_1sj_1sb_ge1ssv_isrb',
#               'negmu_silver_1sj_1sb_ge1ssv_central_noisrb',
#               'negmu_silver_1sj_1sb_ge1ssv_central_isrb',
#               'negmu_silver_1sj_1sb_ge1ssv_forward_noisrb',
#               'negmu_silver_1sj_1sb_ge1ssv_forward_isrb',
#               'negmu_silver_2sj_noisrb',
#               'negmu_silver_2sj_isrb',
#               'negmu_silver_2sj_1sb_noisrb',
#               'negmu_silver_2sj_1sb_isrb',
#               'negmu_silver_2sj_2sb_noisrb',
#               'negmu_silver_2sj_2sb_isrb',
#               'negmu_silver_3sj_noisrb',
#               'negmu_silver_3sj_isrb',
#               'negmu_silver_3sj_ge1sb_noisrb',
#               'negmu_silver_3sj_ge1sb_isrb',
#               'negmu_silver_ge4sj_noisrb',
#               'negmu_silver_ge4sj_isrb',
#               'posel_silver_nos_noisrb',
#               'posel_silver_nos_isrb',
#               'posel_silver_ge1ssv_noisrb',
#               'posel_silver_ge1ssv_isrb',
#               'posel_silver_ge1ssv_central_noisrb',
#               'posel_silver_ge1ssv_central_isrb',
#               'posel_silver_ge1ssv_forward_noisrb',
#               'posel_silver_ge1ssv_forward_isrb',
#               'posel_silver_1sj_noisrb',
#               'posel_silver_1sj_isrb',
#               'posel_silver_1sj_1sb_noisrb',
#               'posel_silver_1sj_1sb_isrb',
#               'posel_silver_1sj_ge1ssv_noisrb',
#               'posel_silver_1sj_ge1ssv_isrb',
#               'posel_silver_1sj_ge1ssv_central_noisrb',
#               'posel_silver_1sj_ge1ssv_central_isrb',
#               'posel_silver_1sj_ge1ssv_forward_noisrb',
#               'posel_silver_1sj_ge1ssv_forward_isrb',
#               'posel_silver_1sj_1sb_ge1ssv_noisrb',
#               'posel_silver_1sj_1sb_ge1ssv_isrb',
#               'posel_silver_1sj_1sb_ge1ssv_central_noisrb',
#               'posel_silver_1sj_1sb_ge1ssv_central_isrb',
#               'posel_silver_1sj_1sb_ge1ssv_forward_noisrb',
#               'posel_silver_1sj_1sb_ge1ssv_forward_isrb',
#               'posel_silver_2sj_noisrb',
#               'posel_silver_2sj_isrb',
#               'posel_silver_2sj_1sb_noisrb',
#               'posel_silver_2sj_1sb_isrb',
#               'posel_silver_2sj_2sb_noisrb',
#               'posel_silver_2sj_2sb_isrb',
#               'posel_silver_3sj_noisrb',
#               'posel_silver_3sj_isrb',
#               'posel_silver_3sj_ge1sb_noisrb',
#               'posel_silver_3sj_ge1sb_isrb',
#               'posel_silver_ge4sj_noisrb',
#               'posel_silver_ge4sj_isrb',
#               'negel_silver_nos_noisrb',
#               'negel_silver_nos_isrb',
#               'negel_silver_ge1ssv_noisrb',
#               'negel_silver_ge1ssv_isrb',
#               'negel_silver_ge1ssv_central_noisrb',
#               'negel_silver_ge1ssv_central_isrb',
#               'negel_silver_ge1ssv_forward_noisrb',
#               'negel_silver_ge1ssv_forward_isrb',
#               'negel_silver_1sj_noisrb',
#               'negel_silver_1sj_isrb',
#               'negel_silver_1sj_1sb_noisrb',
#               'negel_silver_1sj_1sb_isrb',
#               'negel_silver_1sj_ge1ssv_noisrb',
#               'negel_silver_1sj_ge1ssv_isrb',
#               'negel_silver_1sj_ge1ssv_central_noisrb',
#               'negel_silver_1sj_ge1ssv_central_isrb',
#               'negel_silver_1sj_ge1ssv_forward_noisrb',
#               'negel_silver_1sj_ge1ssv_forward_isrb',
#               'negel_silver_1sj_1sb_ge1ssv_noisrb',
#               'negel_silver_1sj_1sb_ge1ssv_isrb',
#               'negel_silver_1sj_1sb_ge1ssv_central_noisrb',
#               'negel_silver_1sj_1sb_ge1ssv_central_isrb',
#               'negel_silver_1sj_1sb_ge1ssv_forward_noisrb',
#               'negel_silver_1sj_1sb_ge1ssv_forward_isrb',
#               'negel_silver_2sj_noisrb',
#               'negel_silver_2sj_isrb',
#               'negel_silver_2sj_1sb_noisrb',
#               'negel_silver_2sj_1sb_isrb',
#               'negel_silver_2sj_2sb_noisrb',
#               'negel_silver_2sj_2sb_isrb',
#               'negel_silver_3sj_noisrb',
#               'negel_silver_3sj_isrb',
#               'negel_silver_3sj_ge1sb_noisrb',
#               'negel_silver_3sj_ge1sb_isrb',
#               'negel_silver_ge4sj_noisrb',
#               'negel_silver_ge4sj_isrb',
#               'bronze_nos_noisrb',
#               'bronze_nos_isrb',
#               'bronze_ge1ssv_noisrb',
#               'bronze_ge1ssv_isrb',
#               'bronze_ge1ssv_central_noisrb',
#               'bronze_ge1ssv_central_isrb',
#               'bronze_ge1ssv_forward_noisrb',
#               'bronze_ge1ssv_forward_isrb',
#               'bronze_1sj_noisrb',
#               'bronze_1sj_isrb',
#               'bronze_1sj_1sb_noisrb',
#               'bronze_1sj_1sb_isrb',
#               'bronze_1sj_ge1ssv_noisrb',
#               'bronze_1sj_ge1ssv_isrb',
#               'bronze_1sj_ge1ssv_central_noisrb',
#               'bronze_1sj_ge1ssv_central_isrb',
#               'bronze_1sj_ge1ssv_forward_noisrb',
#               'bronze_1sj_ge1ssv_forward_isrb',
#               'bronze_1sj_1sb_ge1ssv_noisrb',
#               'bronze_1sj_1sb_ge1ssv_isrb',
#               'bronze_1sj_1sb_ge1ssv_central_noisrb',
#               'bronze_1sj_1sb_ge1ssv_central_isrb',
#               'bronze_1sj_1sb_ge1ssv_forward_noisrb',
#               'bronze_1sj_1sb_ge1ssv_forward_isrb',
#               'bronze_2sj_noisrb',
#               'bronze_2sj_isrb',
#               'bronze_2sj_1sb_noisrb',
#               'bronze_2sj_1sb_isrb',
#               'bronze_2sj_2sb_noisrb',
#               'bronze_2sj_2sb_isrb',
#               'bronze_3sj_noisrb',
#               'bronze_3sj_isrb',
#               'bronze_3sj_ge1sb_noisrb',
#               'bronze_3sj_ge1sb_isrb',
#               'bronze_ge4sj_noisrb',
#               'bronze_ge4sj_isrb',
#               'posmu_bronze_nos_noisrb',
#               'posmu_bronze_nos_isrb',
#               'posmu_bronze_ge1ssv_noisrb',
#               'posmu_bronze_ge1ssv_isrb',
#               'posmu_bronze_ge1ssv_central_noisrb',
#               'posmu_bronze_ge1ssv_central_isrb',
#               'posmu_bronze_ge1ssv_forward_noisrb',
#               'posmu_bronze_ge1ssv_forward_isrb',
#               'posmu_bronze_1sj_noisrb',
#               'posmu_bronze_1sj_isrb',
#               'posmu_bronze_1sj_1sb_noisrb',
#               'posmu_bronze_1sj_1sb_isrb',
#               'posmu_bronze_1sj_ge1ssv_noisrb',
#               'posmu_bronze_1sj_ge1ssv_isrb',
#               'posmu_bronze_1sj_ge1ssv_central_noisrb',
#               'posmu_bronze_1sj_ge1ssv_central_isrb',
#               'posmu_bronze_1sj_ge1ssv_forward_noisrb',
#               'posmu_bronze_1sj_ge1ssv_forward_isrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_noisrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_isrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_central_noisrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_central_isrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_forward_noisrb',
#               'posmu_bronze_1sj_1sb_ge1ssv_forward_isrb',
#               'posmu_bronze_2sj_noisrb',
#               'posmu_bronze_2sj_isrb',
#               'posmu_bronze_2sj_1sb_noisrb',
#               'posmu_bronze_2sj_1sb_isrb',
#               'posmu_bronze_2sj_2sb_noisrb',
#               'posmu_bronze_2sj_2sb_isrb',
#               'posmu_bronze_3sj_noisrb',
#               'posmu_bronze_3sj_isrb',
#               'posmu_bronze_3sj_ge1sb_noisrb',
#               'posmu_bronze_3sj_ge1sb_isrb',
#               'posmu_bronze_ge4sj_noisrb',
#               'posmu_bronze_ge4sj_isrb',
#               'negmu_bronze_nos_noisrb',
#               'negmu_bronze_nos_isrb',
#               'negmu_bronze_ge1ssv_noisrb',
#               'negmu_bronze_ge1ssv_isrb',
#               'negmu_bronze_ge1ssv_central_noisrb',
#               'negmu_bronze_ge1ssv_central_isrb',
#               'negmu_bronze_ge1ssv_forward_noisrb',
#               'negmu_bronze_ge1ssv_forward_isrb',
#               'negmu_bronze_1sj_noisrb',
#               'negmu_bronze_1sj_isrb',
#               'negmu_bronze_1sj_1sb_noisrb',
#               'negmu_bronze_1sj_1sb_isrb',
#               'negmu_bronze_1sj_ge1ssv_noisrb',
#               'negmu_bronze_1sj_ge1ssv_isrb',
#               'negmu_bronze_1sj_ge1ssv_central_noisrb',
#               'negmu_bronze_1sj_ge1ssv_central_isrb',
#               'negmu_bronze_1sj_ge1ssv_forward_noisrb',
#               'negmu_bronze_1sj_ge1ssv_forward_isrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_noisrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_isrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_central_noisrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_central_isrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_forward_noisrb',
#               'negmu_bronze_1sj_1sb_ge1ssv_forward_isrb',
#               'negmu_bronze_2sj_noisrb',
#               'negmu_bronze_2sj_isrb',
#               'negmu_bronze_2sj_1sb_noisrb',
#               'negmu_bronze_2sj_1sb_isrb',
#               'negmu_bronze_2sj_2sb_noisrb',
#               'negmu_bronze_2sj_2sb_isrb',
#               'negmu_bronze_3sj_noisrb',
#               'negmu_bronze_3sj_isrb',
#               'negmu_bronze_3sj_ge1sb_noisrb',
#               'negmu_bronze_3sj_ge1sb_isrb',
#               'negmu_bronze_ge4sj_noisrb',
#               'negmu_bronze_ge4sj_isrb',
#               'posel_bronze_nos_noisrb',
#               'posel_bronze_nos_isrb',
#               'posel_bronze_ge1ssv_noisrb',
#               'posel_bronze_ge1ssv_isrb',
#               'posel_bronze_ge1ssv_central_noisrb',
#               'posel_bronze_ge1ssv_central_isrb',
#               'posel_bronze_ge1ssv_forward_noisrb',
#               'posel_bronze_ge1ssv_forward_isrb',
#               'posel_bronze_1sj_noisrb',
#               'posel_bronze_1sj_isrb',
#               'posel_bronze_1sj_1sb_noisrb',
#               'posel_bronze_1sj_1sb_isrb',
#               'posel_bronze_1sj_ge1ssv_noisrb',
#               'posel_bronze_1sj_ge1ssv_isrb',
#               'posel_bronze_1sj_ge1ssv_central_noisrb',
#               'posel_bronze_1sj_ge1ssv_central_isrb',
#               'posel_bronze_1sj_ge1ssv_forward_noisrb',
#               'posel_bronze_1sj_ge1ssv_forward_isrb',
#               'posel_bronze_1sj_1sb_ge1ssv_noisrb',
#               'posel_bronze_1sj_1sb_ge1ssv_isrb',
#               'posel_bronze_1sj_1sb_ge1ssv_central_noisrb',
#               'posel_bronze_1sj_1sb_ge1ssv_central_isrb',
#               'posel_bronze_1sj_1sb_ge1ssv_forward_noisrb',
#               'posel_bronze_1sj_1sb_ge1ssv_forward_isrb',
#               'posel_bronze_2sj_noisrb',
#               'posel_bronze_2sj_isrb',
#               'posel_bronze_2sj_1sb_noisrb',
#               'posel_bronze_2sj_1sb_isrb',
#               'posel_bronze_2sj_2sb_noisrb',
#               'posel_bronze_2sj_2sb_isrb',
#               'posel_bronze_3sj_noisrb',
#               'posel_bronze_3sj_isrb',
#               'posel_bronze_3sj_ge1sb_noisrb',
#               'posel_bronze_3sj_ge1sb_isrb',
#               'posel_bronze_ge4sj_noisrb',
#               'posel_bronze_ge4sj_isrb',
#               'negel_bronze_nos_noisrb',
#               'negel_bronze_nos_isrb',
#               'negel_bronze_ge1ssv_noisrb',
#               'negel_bronze_ge1ssv_isrb',
#               'negel_bronze_ge1ssv_central_noisrb',
#               'negel_bronze_ge1ssv_central_isrb',
#               'negel_bronze_ge1ssv_forward_noisrb',
#               'negel_bronze_ge1ssv_forward_isrb',
#               'negel_bronze_1sj_noisrb',
#               'negel_bronze_1sj_isrb',
#               'negel_bronze_1sj_1sb_noisrb',
#               'negel_bronze_1sj_1sb_isrb',
#               'negel_bronze_1sj_ge1ssv_noisrb',
#               'negel_bronze_1sj_ge1ssv_isrb',
#               'negel_bronze_1sj_ge1ssv_central_noisrb',
#               'negel_bronze_1sj_ge1ssv_central_isrb',
#               'negel_bronze_1sj_ge1ssv_forward_noisrb',
#               'negel_bronze_1sj_ge1ssv_forward_isrb',
#               'negel_bronze_1sj_1sb_ge1ssv_noisrb',
#               'negel_bronze_1sj_1sb_ge1ssv_isrb',
#               'negel_bronze_1sj_1sb_ge1ssv_central_noisrb',
#               'negel_bronze_1sj_1sb_ge1ssv_central_isrb',
#               'negel_bronze_1sj_1sb_ge1ssv_forward_noisrb',
#               'negel_bronze_1sj_1sb_ge1ssv_forward_isrb',
#               'negel_bronze_2sj_noisrb',
#               'negel_bronze_2sj_isrb',
#               'negel_bronze_2sj_1sb_noisrb',
#               'negel_bronze_2sj_1sb_isrb',
#               'negel_bronze_2sj_2sb_noisrb',
#               'negel_bronze_2sj_2sb_isrb',
#               'negel_bronze_3sj_noisrb',
#               'negel_bronze_3sj_isrb',
#               'negel_bronze_3sj_ge1sb_noisrb',
#               'negel_bronze_3sj_ge1sb_isrb',
#               'negel_bronze_ge4sj_noisrb',
#               'negel_bronze_ge4sj_isrb',
    ]

for plot in plot_configurables.copy():
    for sel in selections:
        plot_configurables[plot + '_' + sel] = plot_configurables[plot].copy()
